### ISSUE TITLE
Header way too large when using Safari browser

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/slicer.org#75]
The new Slicer website design has a flaw where the main header is way too large as seen when scrolling down the page. It covers a majority of the screen preventing you from reading most of the content.

Impacts Desktop Safari on a Mac and Mobile Safari on an iPhone
![safari-screenshot](https://user-images.githubusercontent.com/15837524/112164918-ac918180-8bc4-11eb-839b-9149d9bfafd4.jpg)

![8847C38D-C427-4489-AC9B-6EA4E2498E4B](https://user-images.githubusercontent.com/15837524/111646969-7b860b00-87d8-11eb-937a-b361f0895188.jpeg)

**Comment by lassoan** [comment]
@jcfr I think this would need to be fixed before the site goes live - or hide this header completely (the content is repeated in the footer anyway).

**Comment by jcfr** [comment]
Agreed, I will push a fix shortly

**Comment by jcfr** [comment]
This has been fixed, @jamesobutler Could you have another look ?

**Comment by jamesobutler** [comment]
Unfortunately not fixed completely. The logo is not inside the new smaller header size. It is still floating around the middle of the page. It should be inside the header.
![FB97BDF8-8CA6-4CC6-B07D-CC65593B73E4](https://user-images.githubusercontent.com/15837524/112468438-a1faf780-8d3e-11eb-8160-6353898c9394.jpeg)

**Comment by jamesobutler** [comment]
Looks fixed now
![78ED4FB9-0FCE-4D08-A9B8-424F54527C13](https://user-images.githubusercontent.com/15837524/112536508-f4123c00-8d83-11eb-9fa7-8844668eaeb9.jpeg)

**Comment by jcfr** [comment]
Thanks for testing, I need to fix the link to commercial use page,  then I will move forward with the transition.

It  will likely happen this evening after I am back from the :climbing: gym

**Comment by jcfr** [comment]
Thanks for testing :pray:
